@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Report Details</h5>
                    <a href="{{ route('reports.index') }}" class="btn btn-secondary btn-sm">Back</a>
                </div>

                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-md-3 fw-bold">Report ID:</div>
                        <div class="col-md-9">{{ $report->report_id }}</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-3 fw-bold">Report Type:</div>
                        <div class="col-md-9">
                            <span class="badge bg-secondary">{{ $report->report_type }}</span>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-3 fw-bold">Report Date:</div>
                        <div class="col-md-9">{{ \Carbon\Carbon::parse($report->report_date)->format('d/m/Y') }}</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-3 fw-bold">Generated By:</div>
                        <div class="col-md-9">{{ $report->generatedBy->full_name ?? 'N/A' }}</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-3 fw-bold">File Path:</div>
                        <div class="col-md-9">
                            @if($report->file_path)
                                <a href="{{ asset($report->file_path) }}" class="btn btn-success btn-sm" download>
                                    <i class="fas fa-download"></i> Download Report
                                </a>
                            @else
                                <span class="text-muted">No file available</span>
                            @endif
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-3 fw-bold">Created At:</div>
                        <div class="col-md-9">{{ $report->created_at ? $report->created_at->format('d/m/Y H:i') : 'N/A' }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection